services:
  postgres:
    container_name: shipment-tracker-sql
    image: postgres:17.5
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: omar
      PGDATA: /data/postgres
      POSTGRES_DB: shipment_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:
