CREATE TABLE shipment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP                               NOT NULL,
    last_modified_date TIMESTAMP,
    tracking_number    VARCHAR(255)                            NOT NULL,
    origin             VARCHAR(255)                            NOT NULL,
    destination        VARCHAR(255)                            NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    current_location   VARCHAR(255),
    estimated_delivery VARCHAR(255),
    CONSTRAINT pk_shipment PRIMARY KEY (id)
);

ALTER TABLE shipment
    ADD CONSTRAINT uc_shipment_trackingnumber UNIQUE (tracking_number);